"""
Alert API routes.

Author: HAMAILI Ahmed-Imad
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models.alert import Alert
from app.schemas.alert import AlertOut

router = APIRouter(prefix="/alerts", tags=["Alerts"])


@router.get("", response_model=list[AlertOut])
def list_alerts(
    limit: int = Query(default=50, ge=1, le=500),
    db: Session = Depends(get_db),
):
    """Return the latest alerts generated by anomaly rules."""

    return db.query(Alert).order_by(Alert.created_at.desc()).limit(limit).all()
